### ISSUE TITLE
More work?

### ISSUE THREAD

**Issue by lukeeey** [StormxBlur/MC-PE-Server#4]
Will you continue to work on this by adding packet handling?

**Comment by lukeeey** [comment]
I'm also not sure how to decode the unconnected ping packet then send the unconnected pong packet :/

**Comment by Kworz** [comment]
the unconnected ping response is done natively by RakNet

Server.cpp : `PeerInterface->SetOfflinePingResponse(message.c_str(), message.size());`

**Comment by lukeeey** [comment]
Well clearly not, since the client sends a 0x01, which i need to read a long from and then send a 0x1c with that long. Apparently. 

0x01 is the only packet sent from the client and the client goes to an outdated server screen after 10 seconds.

I know 0x01 is also the LogjnPacket ID, but MCPE packets are wrapped in a batch packet (0xFE), and i dont receive one of those. 

0x01: http://wiki.vg/Pocket_Edition_Protocol_Documentation#Unconnected_Ping

The wiki does not list 0x1c, but i was told by someone the pong is that

Well tbh i have no idea what im talking about. https://github.com/ProjectKatana/Katana.

**Comment by lukeeey** [comment]
My other problem is i dont know how to read or write bytes using RakNet :/

**Comment by lukeeey** [comment]
@StormxBlur I also get an outdated server message when my mcpe version protocol is 137

![screenshot_2017-11-13-16-50-31](https://user-images.githubusercontent.com/32024335/32737898-3dcf0e72-c893-11e7-99e6-ca3f7be0605a.png)
![screenshot_2017-11-13-16-46-40](https://user-images.githubusercontent.com/32024335/32737902-41a0dfe4-c893-11e7-867a-2ab13b4ad6b5.png)

**Comment by Kworz** [comment]
are you launching your server and minecraft on the same device ?

**Comment by lukeeey** [comment]
Yes but that is never a problem with PMMP and it shouldnt be saying outdated server.

**Comment by Kworz** [comment]
Change your protocol number to 107 it will work
#define MCPE_PROTOCOL "107"
MCPE tells you that the server is outdated if your protocol number is not the same as the server protocol number

**Comment by lukeeey** [comment]
You aren't looking at my screenshots. The client tells me the protocol is 137, so i set it to 137 on the server.

**Comment by Kworz** [comment]
I have the same protocol number (137) in my game and i still use 107 and it works.
Protocol 137 that MCPE gives you is Internal raknet protocol Number.

**Comment by lukeeey** [comment]
I was told i need to change the Unconnected Pong ID from 0x02 to 0x1c in the RakNet source.

**Comment by Kworz** [comment]
Raknet manage natively Offlinepingresponse you have nothing to change at all.

**Comment by lukeeey** [comment]
I'm aware but still. I can't find where the ID_UNCONNECTED_PONG id is actually defined.

**Comment by Kworz** [comment]
There is something you dont understand, ID_UNCCONECTED_PONG is not handled like the other Raknet native packets. You are searching the problem not in the correct place. Your packet is sent successfully the only thing that is wrong is you MCPE_PROTOCOL that should be equal to 107.

![screenshot_6](https://user-images.githubusercontent.com/8093800/32796091-f6ea9cac-c96d-11e7-9534-1b208c44f320.png)

![screenshot_7](https://user-images.githubusercontent.com/8093800/32796110-0764dfb6-c96e-11e7-8d54-809756fd6603.png)

**Comment by lukeeey** [comment]
Nope.

![screenshot_2017-11-14-18-05-40](https://user-images.githubusercontent.com/32024335/32796500-d8e203be-c966-11e7-9071-0b38aa0b1edb.png)
![screenshot_2017-11-14-18-05-35](https://user-images.githubusercontent.com/32024335/32796509-dca35c96-c966-11e7-8701-61fa80c8ed86.png)
![screenshot_2017-11-14-18-08-22](https://user-images.githubusercontent.com/32024335/32796514-df68c63c-c966-11e7-9aa0-82841e1d8422.png)

**Comment by Kworz** [comment]
haha mybad i thought u were having trouble to get the server displayed in the server list.

The unconnected ping / pong packets are for lan discovery not for the server connection. it changes nothing the connection system.

If MCPE tells you that server is outdated its simply because you havent added the client connection handling.

**Comment by lukeeey** [comment]
But the only packet i receive is the 0x01 ping packet wtf do i do to receive more packets

**Comment by Kworz** [comment]
For me when i just read packets, if i connect to my server i get 0x13 & 0xFE
![screenshot_8](https://user-images.githubusercontent.com/8093800/32797439-0e139e66-c972-11e7-9609-4e34e32e0320.png)
